import {
  useEffect,
  useRef,
  useState,
  type ChangeEvent,
  type FormEvent,
  type KeyboardEvent,
} from "react";

import * as api from "../../api";
import { ApiError } from "../../api/client";
import { useTwins } from "../../state/TwinContext";
import type { ChatMessage, Conversation } from "../../lib/conversations";
import { Button, EmptyState, ErrorNotice, Spinner } from "../ui";
import { SourceList } from "./SourceCard";
import { UploadTray } from "./UploadTray";

interface Props {
  conversation: Conversation;
  onMessages: (messages: ChatMessage[]) => void;
  onIngested: () => void;
  onNewConversation: () => void;
}

export function ChatPanel({
  conversation,
  onMessages,
  onIngested,
  onNewConversation,
}: Props) {
  const { currentTwin } = useTwins();
  const [draft, setDraft] = useState("");
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  const messages = conversation.messages;
  const lastSourceCount =
    [...messages].reverse().find((message) => message.role === "assistant")?.sources
      ?.length ?? 0;

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ block: "end" });
  }, [messages.length, pending]);

  async function ask(question: string) {
    if (!currentTwin) return;

    const asked: ChatMessage = {
      id: `${Date.now()}-user`,
      role: "user",
      text: question,
    };

    const withQuestion = [...messages, asked];
    onMessages(withQuestion);
    setDraft("");
    setPending(true);
    setError(null);

    try {
      const answer = await api.askQuestion(question, currentTwin.id);

      onMessages([
        ...withQuestion,
        {
          id: `${Date.now()}-assistant`,
          role: "assistant",
          text: answer.answer,
          sources: answer.sources,
          retrievedChunks: answer.retrieved_chunks,
        },
      ]);
    } catch (cause) {
      // The question stays in the transcript so it can be retried without
      // being retyped.
      setError(
        cause instanceof ApiError
          ? cause.message
          : "Could not reach the backend. Check that it is running.",
      );
    } finally {
      setPending(false);
    }
  }

  function submit(event: FormEvent) {
    event.preventDefault();
    const question = draft.trim();
    if (question && !pending) void ask(question);
  }

  return (
    <section className="flex h-full min-w-0 flex-col bg-white">
      <header className="flex items-start justify-between gap-4 border-b border-ink-200 px-6 py-4">
        <div className="min-w-0">
          <h1 className="truncate text-base font-semibold text-ink-900">
            {currentTwin
              ? `${currentTwin.name} · ${currentTwin.role}`
              : "No Digital Twin selected"}
          </h1>
          <p className="mt-0.5 text-xs text-ink-500">
            Digital Twin
            {conversation.title !== "New conversation"
              ? ` · ${conversation.title}`
              : ""}
          </p>
        </div>
        <Button type="button" onClick={onNewConversation} className="shrink-0">
          New conversation
        </Button>
      </header>

      {/* What is actually in play for the next answer: the twin's private
          context, the shared corpus, and how many passages the last answer
          was grounded in. */}
      <div className="flex flex-wrap items-center gap-x-5 gap-y-1 border-b border-ink-200 bg-ink-50/70 px-6 py-2 text-xs text-ink-600">
        <span>
          Digital Twin:{" "}
          <span className="font-medium text-ink-800">
            {currentTwin ? currentTwin.name : "none"}
          </span>
        </span>
        <span>
          Knowledge base:{" "}
          <span className="font-medium text-ink-800">shared corpus</span>
        </span>
        <span>
          Sources in last answer:{" "}
          <span className="font-medium text-ink-800">{lastSourceCount}</span>
        </span>
      </div>

      <div className="flex-1 overflow-y-auto">
        {messages.length === 0 ? (
          <EmptyState
            title="Ask your Digital Twin"
            description="Ask about proposals, clients, capabilities, technical topics or anything else in the SunRadia knowledge base. Answers are generated by the language model, grounded in retrieved documents, and shaped by this twin's profile and memory. Every answer lists the passages it drew on."
          />
        ) : (
          <ol className="mx-auto max-w-3xl space-y-5 px-5 py-5">
            {messages.map((message) => (
              <li key={message.id}>
                <Message message={message} />
              </li>
            ))}
            {pending ? (
              <li>
                <div className="text-xs font-semibold uppercase tracking-wide text-ink-500">
                  Digital Twin
                </div>
                <div className="mt-1.5">
                  <Spinner label="Searching your documents…" />
                </div>
              </li>
            ) : null}
          </ol>
        )}
        <div ref={bottomRef} />
      </div>

      <div className="border-t border-ink-200 bg-ink-50/60 px-5 py-3">
        <div className="mx-auto max-w-3xl space-y-2.5">
          {error ? <ErrorNotice message={error} /> : null}

          <UploadTray onIngested={onIngested} />

          <form onSubmit={submit} className="flex items-end gap-2">
            <label htmlFor="chat-input" className="sr-only">
              Ask a question
            </label>
            <textarea
              id="chat-input"
              rows={2}
              value={draft}
              disabled={!currentTwin || pending}
              onChange={(event: ChangeEvent<HTMLTextAreaElement>) =>
                setDraft(event.target.value)
              }
              onKeyDown={(event: KeyboardEvent<HTMLTextAreaElement>) => {
                // Enter sends, Shift+Enter breaks the line — the convention
                // people already have from every other chat surface.
                if (event.key === "Enter" && !event.shiftKey) {
                  event.preventDefault();
                  const question = draft.trim();
                  if (question && !pending) void ask(question);
                }
              }}
              placeholder={
                currentTwin
                  ? "Ask about anything in the knowledge base…"
                  : "Select a user to start"
              }
              className="min-h-[2.75rem] flex-1 resize-y rounded-md border border-ink-200 bg-white px-3 py-2 text-sm leading-relaxed placeholder:text-ink-400 disabled:bg-ink-100"
            />
            <Button
              type="submit"
              variant="primary"
              disabled={!currentTwin || pending || !draft.trim()}
              className="h-[2.75rem] px-4"
            >
              Send
            </Button>
          </form>

          <p className="text-xs text-ink-500">
            The selected user&rsquo;s profile and memories shape how answers are
            written. They are not sources and are never cited.
          </p>
        </div>
      </div>
    </section>
  );
}

function Message({ message }: { message: ChatMessage }) {
  if (message.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="max-w-[85%] rounded-lg bg-accent-600 px-3.5 py-2 text-sm leading-relaxed text-white">
          {message.text}
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="text-xs font-semibold uppercase tracking-wide text-ink-500">
        Digital Twin
      </div>
      <div className="mt-1.5 whitespace-pre-wrap text-sm leading-relaxed text-ink-800">
        {message.text}
      </div>
      {message.sources && message.sources.length > 0 ? (
        <SourceList sources={message.sources} />
      ) : message.retrievedChunks === 0 ? (
        <p className="mt-2 text-xs text-ink-500">
          Nothing in the knowledge base matched this question.
        </p>
      ) : null}
    </div>
  );
}
