/**
 * The Email Agent's logic, kept out of the components so it can be tested.
 *
 * Everything here is a pure function over the API's types. The components
 * render what these return; they do not decide what a status means, whether a
 * draft is ready, or which follow-up is overdue.
 *
 * Two rules are encoded here rather than in a component, because they are the
 * ones a redesign would otherwise quietly lose:
 *
 * 1. **"Sent" is only ever shown for `status === "sent"`**, which the backend
 *    writes only on a provider receipt. `describeDraftStatus` has no branch
 *    that produces "Sent" from anything else.
 * 2. **A draft is only sendable when the backend would accept it** — approved,
 *    with recipients, and with a mailbox connected. `sendBlockers` returns the
 *    reasons, so the UI explains rather than merely disables.
 */

import type {
  EmailAssessment,
  EmailCategory,
  EmailDraft,
  EmailDraftStatus,
  EmailOperation,
  EmailPriority,
  EmailProviderStatus,
  EmailTemplate,
} from "../api/types";

export type Tone = "positive" | "neutral" | "warning" | "danger" | "info";

// --- draft status --------------------------------------------------------

export interface StatusPresentation {
  label: string;
  tone: Tone;
  hint: string;
}

const DRAFT_STATUS: Record<EmailDraftStatus, StatusPresentation> = {
  draft: {
    label: "Draft",
    tone: "neutral",
    hint: "Being written. Cannot be sent yet.",
  },
  needs_review: {
    label: "Needs review",
    tone: "warning",
    hint: "Generated by the assistant. Nobody has read it yet.",
  },
  approved: {
    label: "Ready to send",
    tone: "info",
    hint: "Reviewed and approved. Editing it withdraws the approval.",
  },
  sending: {
    label: "Sending",
    tone: "info",
    hint: "Handed to the mailbox. The outcome is not known yet.",
  },
  sent: {
    label: "Sent",
    tone: "positive",
    hint: "Confirmed by the mailbox provider.",
  },
  failed: {
    label: "Failed",
    tone: "danger",
    hint: "The provider did not send it. Correct it and approve again.",
  },
};

export function describeDraftStatus(status: EmailDraftStatus): StatusPresentation {
  return DRAFT_STATUS[status];
}

/**
 * Whether the assistant wrote any of this, and a person has not yet read it.
 * Rendered as a distinct badge — someone reviewing text should know whether
 * they or a model produced it.
 */
export function isAwaitingReview(draft: EmailDraft): boolean {
  return draft.status === "needs_review";
}

export function isEditable(draft: EmailDraft): boolean {
  return draft.status !== "sent" && draft.status !== "sending";
}

// --- the send gate -------------------------------------------------------

/**
 * Why this draft cannot be sent, in the order a person would fix them.
 *
 * Mirrors the backend's checks rather than guessing at them: recipients,
 * subject and body are required at approval; approval is required at send; a
 * mailbox is required for the provider call. An empty array means the backend
 * would accept a send.
 */
export function sendBlockers(
  draft: EmailDraft,
  provider: EmailProviderStatus | null,
): string[] {
  const blockers: string[] = [];

  if (draft.status === "sent") return ["This email has already been sent."];
  if (draft.status === "sending") return ["This email is being sent."];

  if (draft.to_recipients.length === 0) blockers.push("Add at least one recipient.");
  if (!draft.subject.trim()) blockers.push("Add a subject.");
  if (!draft.body.trim()) blockers.push("Write a message.");

  if (draft.status !== "approved") {
    blockers.push("Review the draft and approve it.");
  }

  if (!provider?.connected) {
    blockers.push("Connect a mailbox on the server before sending.");
  }

  return blockers;
}

/** Whether approval is currently possible — the checks the backend applies. */
export function approvalBlockers(draft: EmailDraft): string[] {
  const blockers: string[] = [];

  if (draft.status === "sent") return ["This email has already been sent."];
  if (draft.status === "sending") return ["This email is being sent."];

  if (draft.to_recipients.length === 0) blockers.push("Add at least one recipient.");
  if (!draft.subject.trim()) blockers.push("Add a subject.");
  if (!draft.body.trim()) blockers.push("Write a message.");

  return blockers;
}

// --- recipients ----------------------------------------------------------

/**
 * Split what someone typed into addresses.
 *
 * Commas, semicolons and newlines all separate, because people paste from all
 * three. Duplicates are removed case-insensitively while order is kept — the
 * first name on a To line is usually the person being asked.
 */
export function parseRecipients(value: string): string[] {
  const parts = value
    .split(/[,;\n]/)
    .map((item) => item.trim())
    .filter(Boolean);

  const seen = new Set<string>();
  const result: string[] = [];

  for (const part of parts) {
    const key = part.toLowerCase();
    if (seen.has(key)) continue;

    seen.add(key);
    result.push(part);
  }

  return result;
}

/**
 * A shape check, matching the backend's `validate_recipients`. Not RFC 5322:
 * the point is to catch "jsmith" and "john smith@x.com" before a request, not
 * to adjudicate what a legal address is.
 *
 * Whitespace anywhere is refused. `parseRecipients` trims the outside, so a
 * space that survives is a name typed where an address belongs, or two
 * addresses pasted without a separator. Keeping this rule identical to the
 * backend's is what stops the UI accepting something the API will reject.
 */
export function isPlausibleAddress(address: string): boolean {
  if (/\s/.test(address)) return false;

  const parts = address.split("@");

  if (parts.length !== 2) return false;

  const [local, domain] = parts;

  return Boolean(local) && domain.includes(".") && !domain.startsWith(".");
}

export function invalidRecipients(addresses: string[]): string[] {
  return addresses.filter((address) => !isPlausibleAddress(address));
}

// --- triage --------------------------------------------------------------

const CATEGORY: Record<EmailCategory, { label: string; tone: Tone }> = {
  urgent: { label: "Urgent", tone: "danger" },
  needs_reply: { label: "Needs reply", tone: "warning" },
  follow_up: { label: "Follow-up", tone: "info" },
  fyi: { label: "FYI", tone: "neutral" },
  low_priority: { label: "Low priority", tone: "neutral" },
};

export function describeCategory(category: EmailCategory): {
  label: string;
  tone: Tone;
} {
  return CATEGORY[category];
}

const PRIORITY: Record<EmailPriority, { label: string; tone: Tone }> = {
  high: { label: "High", tone: "danger" },
  normal: { label: "Normal", tone: "neutral" },
  low: { label: "Low", tone: "neutral" },
};

export function describePriority(priority: EmailPriority): {
  label: string;
  tone: Tone;
} {
  return PRIORITY[priority];
}

/**
 * The order categories are shown in — most demanding first.
 *
 * Untriaged messages sort last rather than first. A message nobody has judged
 * is not "unimportant"; it is unknown, and putting unknowns above things
 * already known to be urgent would bury the urgent ones.
 */
const CATEGORY_ORDER: EmailCategory[] = [
  "urgent",
  "needs_reply",
  "follow_up",
  "fyi",
  "low_priority",
];

export function categoryRank(category: EmailCategory | null): number {
  if (category === null) return CATEGORY_ORDER.length;

  return CATEGORY_ORDER.indexOf(category);
}

export interface CategoryGroup<T> {
  category: EmailCategory | null;
  label: string;
  items: T[];
}

/** Group triaged rows by category, in the order above, dropping empty groups. */
export function groupByCategory<T>(
  rows: T[],
  categoryOf: (row: T) => EmailCategory | null,
): CategoryGroup<T>[] {
  const groups: CategoryGroup<T>[] = [];

  const keys: (EmailCategory | null)[] = [...CATEGORY_ORDER, null];

  for (const key of keys) {
    const items = rows.filter((row) => categoryOf(row) === key);

    if (items.length === 0) continue;

    groups.push({
      category: key,
      label: key === null ? "Not yet triaged" : CATEGORY[key].label,
      items,
    });
  }

  return groups;
}

// --- follow-ups ----------------------------------------------------------

/**
 * Is this follow-up past its date?
 *
 * Only ever true when the *message* gave a date. The backend never invents
 * one, so an undated follow-up is never overdue — it is simply outstanding.
 */
export function isOverdue(assessment: EmailAssessment, now: number): boolean {
  if (!assessment.follow_up_due_at || assessment.handled) return false;

  const due = new Date(assessment.follow_up_due_at).getTime();

  return Number.isFinite(due) && due <= now;
}

/**
 * Follow-ups in the order the backend returns them, which is soonest-due
 * first with undated ones last. Re-sorting here would be a second opinion
 * with less information; this only partitions overdue from the rest so the
 * UI can head them separately.
 */
export function partitionFollowUps(
  assessments: EmailAssessment[],
  now: number,
): { overdue: EmailAssessment[]; upcoming: EmailAssessment[] } {
  return {
    overdue: assessments.filter((item) => isOverdue(item, now)),
    upcoming: assessments.filter((item) => !isOverdue(item, now)),
  };
}

// --- templates -----------------------------------------------------------

/** Which placeholders a template still needs, given what has been typed. */
export function missingPlaceholders(
  template: EmailTemplate,
  values: Record<string, string>,
): string[] {
  return template.placeholders.filter((name) => !(values[name] ?? "").trim());
}

export function searchTemplates(
  templates: EmailTemplate[],
  query: string,
): EmailTemplate[] {
  const needle = query.trim().toLowerCase();

  if (!needle) return templates;

  return templates.filter((template) =>
    [template.name, template.description ?? "", template.category]
      .join(" ")
      .toLowerCase()
      .includes(needle),
  );
}

// --- operations ----------------------------------------------------------

export interface OperationChoice {
  operation: EmailOperation;
  label: string;
  /** Whether it needs an existing draft body to act on. */
  needsBody: boolean;
  needsTone?: boolean;
}

/**
 * The revision buttons, in the order they appear above the editor. Data rather
 * than markup, so the set is testable and adding one is a line here.
 */
export const REVISION_OPERATIONS: OperationChoice[] = [
  { operation: "rewrite", label: "Rewrite", needsBody: true },
  { operation: "improve", label: "Improve clarity", needsBody: true },
  { operation: "shorten", label: "Shorten", needsBody: true },
  { operation: "expand", label: "Expand", needsBody: true },
  { operation: "professional", label: "More professional", needsBody: true },
  { operation: "concise", label: "More concise", needsBody: true },
  { operation: "change_tone", label: "Change tone", needsBody: true, needsTone: true },
  { operation: "subject", label: "Suggest subject", needsBody: true },
];

/** Why an operation is unavailable right now, or null if it is available. */
export function operationBlocker(
  choice: OperationChoice,
  state: { body: string; tone: string },
): string | null {
  if (choice.needsBody && !state.body.trim()) {
    return "Write or generate a message first.";
  }

  if (choice.needsTone && !state.tone.trim()) {
    return "Say which tone you want.";
  }

  return null;
}

// --- provider ------------------------------------------------------------

/** How to describe the mailbox connection, without ever implying one exists. */
export function describeProvider(status: EmailProviderStatus | null): {
  label: string;
  tone: Tone;
} {
  if (!status || !status.configured) {
    return { label: "Not connected", tone: "neutral" };
  }

  if (!status.connected) return { label: "Connection failed", tone: "danger" };

  return { label: "Connected", tone: "positive" };
}
